### ISSUE TITLE
Any plans to release fine-tuned weights?

### ISSUE THREAD

**Issue by anupamsobti** [gruberto/PixelAccurateDepthBenchmark#3]
Hi

Thanks for sharing the code and data for evaluation. Please let us know if you also plan to release the fine-tuned monodepth/sparse2dense weights so that we could reproduce the results. Currently, only the outputs of the methods are available from the dataset download page.

**Comment by gruberto** [comment]
Thanks for your interest in the benchmark. The purpose of this benchmark is to make different methods easily comparable. Therefore, each researcher is invited to evaluate its own models on this dataset. The models can be developed/finetuned on the Gated2Depth dataset (see https://arxiv.org/abs/1902.04997) or the Seeing Through Fog dataset (https://arxiv.org/abs/1902.08913). Both datasets provide exactly the same sensor setup. 
There is no need to share the models' weights as the models generate exactly the output that is already provided. This is sufficient to compare all current models against new approaches.

**Comment by anupamsobti** [comment]
Thanks for confirming.
