### ISSUE TITLE
Baseline of the stereo camera

### ISSUE THREAD

**Issue by tedyiningding** [gruberto/PixelAccurateDepthBenchmark#4]
Hi,

Thanks for the dataset and the great work!

Could you please advise where to find the baseline of the stereo camera?

Many thanks,
Ted

**Comment by gruberto** [comment]
You find the baseline of the stereo camera in src/Evaluator.py in line 16 (bfl_rgb).

**Comment by tedyiningding** [comment]
Thanks for the reply!

Best wishes,
Ted
